"""empty message

Revision ID: 00fafc231b6c
Revises: 1c07823ddf30
Create Date: 2021-03-27 13:32:45.656293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fafc231b6c'
down_revision = '1c07823ddf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('raw_record', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'raw_record')
    # ### end Alembic commands ###
