"""empty message

Revision ID: 3375fb28bc2e
Revises: 00fafc231b6c
Create Date: 2021-03-28 00:05:11.203798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3375fb28bc2e'
down_revision = '00fafc231b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('overall_batch_comparison_dict', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'overall_batch_comparison_dict')
    # ### end Alembic commands ###
