"""empty message

Revision ID: 68114a798c7a
Revises: 6fe5f5354dac
Create Date: 2021-03-30 07:36:17.429168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68114a798c7a'
down_revision = '6fe5f5354dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('records_tally', sa.Integer(), nullable=True))
    op.add_column('batches', sa.Column('records_w_no_oclc_match', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'records_w_no_oclc_match')
    op.drop_column('batches', 'records_tally')
    # ### end Alembic commands ###
