"""empty message

Revision ID: ad8acfc66ca2
Revises: 68114a798c7a
Create Date: 2021-04-01 12:12:50.160262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8acfc66ca2'
down_revision = '68114a798c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'title')
    # ### end Alembic commands ###
