"""empty message

Revision ID: b5e2c0a04e27
Revises: 3375fb28bc2e
Create Date: 2021-03-29 12:05:19.287728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e2c0a04e27'
down_revision = '3375fb28bc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('field_count', sa.Integer(), nullable=True))
    op.add_column('records', sa.Column('oclc_match_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'oclc_match_id')
    op.drop_column('records', 'field_count')
    # ### end Alembic commands ###
