"""empty message

Revision ID: c1197f8a206e
Revises: ad8acfc66ca2
Create Date: 2021-04-04 16:14:57.821793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1197f8a206e'
down_revision = 'ad8acfc66ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('identifier_field', sa.String(length=10), nullable=True))
    op.add_column('batches', sa.Column('namespaces', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'notes')
    op.drop_column('batches', 'namespaces')
    op.drop_column('batches', 'identifier_field')
    # ### end Alembic commands ###
