"""empty message

Revision ID: c7e6ea8e35d6
Revises: 973609779c16
Create Date: 2021-04-08 10:31:28.733633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e6ea8e35d6'
down_revision = '973609779c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('from_oclc', sa.Boolean(), nullable=True))
    op.add_column('records', sa.Column('oclc_main_record_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'oclc_main_record_id')
    op.drop_column('records', 'from_oclc')
    # ### end Alembic commands ###
